---
abstract: 'Mojolicious::Services 是为Mojolicious框架提供的Service管理插件。'
author:
  - 'wfso <461663376@qq.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.3, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Services
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: '7.48'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/wfso/Mojolicious-Services/issues
  homepage: http://mojolicious.org
  license: https://opensource.org/licenses/MIT
  repository: https://github.com/wfso/Mojolicious-Services.git
version: v1.0.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
